#!/usr/bin/env python3
import subprocess
import json
import os

def ssh_update_known_hosts(ip):
    print(f"updating known_hosts for {ip} ...")
    subprocess.run(["ssh-keygen", "-R", ip], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    try:
        keyscan = subprocess.check_output(["ssh-keyscan", "-T", "5", ip], stderr=subprocess.DEVNULL)
        with open(os.path.expanduser("~/.ssh/known_hosts"), "a") as kh:
            kh.write(keyscan.decode())
        print(f"added host key для {ip}")
    except Exception as e:
        print(f"error for {ip}: {e}")

user = input("enter username for cloudinit VM`s [user]: ") or "user"
keyfile = input("enter path to ssh_private_key_file [/root/.ssh/id_rsa]: ") or "/root/.ssh/id_rsa"

tf_json = subprocess.check_output(["terraform", "-chdir=terraform", "output", "-json", "nodes_with_roles"])
nodes = json.loads(tf_json) # { name: { ip, role, vmid, node, target_store, current_store, needs_migration } }

masters = []
workers = []
nodes_needing_migration = []

for name, meta in nodes.items():
    if meta["role"] == "master":
        masters.append(meta["ip"])
    elif meta["role"] == "worker":
        workers.append(meta["ip"])
    
    if meta.get("needs_migration", False):
        nodes_needing_migration.append(meta["ip"])

if not masters:
    raise SystemExit("no one Master in terraform output nodes_with_roles.")

master_ip = masters[0]

print("\n--- Updating known_hosts ---")
all_ips = masters + workers
for ip in all_ips:
    ssh_update_known_hosts(ip)

os.makedirs("ansible", exist_ok=True)

hosts_content = [
    "[k3s_masters]",
    *masters,
    "",
    "[k3s_workers]", 
    *workers,
    "",
    "[storage_migration]",
    *nodes_needing_migration,
    "",
    "[all:vars]",
    "ansible_python_interpreter=/usr/bin/python3",
    f"ansible_user={user}",
    f"ansible_ssh_private_key_file={keyfile}"
]

with open("ansible/hosts", "w") as f:
    f.write("\n".join(hosts_content) + "\n")

print("ansible/hosts created:")
print(open("ansible/hosts").read())

gv_path = "ansible/group_vars"
os.makedirs(gv_path, exist_ok=True)
all_yml = f'''k3s_version: "v1.31.6+k3s1"
k3s_master_ip: "{master_ip}"
k3s_tls_sans:
  - "{{{{ k3s_master_ip }}}}"
k3s_server_args:
  - "--disable traefik"
  - "--write-kubeconfig-mode 644"
  - "--tls-san {{{{ k3s_master_ip }}}}"
  - "--node-ip {{{{ ansible_host | default(k3s_master_ip) }}}}"
k3s_agent_args: []
'''
with open(os.path.join(gv_path, "all.yml"), "w") as f:
    f.write(all_yml)

print("ansible/group_vars/all.yml created:")
print(open(os.path.join(gv_path, "all.yml")).read())

hv_path = "ansible/host_vars"
os.makedirs(hv_path, exist_ok=True)

ip_to_entry = {}
for name, meta in nodes.items():
    ip_to_entry[meta["ip"]] = {"name": name, **meta}

created = []
for ip in all_ips:
    entry = ip_to_entry.get(ip)
    if not entry:
        print(f"warning: terraform output has no metadata for ip {ip}, skipping host_vars")
        continue

    hv_file = os.path.join(hv_path, f"{ip}.yml")
    content = f'''# Autogenerated host_vars for {ip}
name: {entry["name"]}
vmid: {entry.get("vmid")}
proxmox_node: {entry.get("node")}
role: {entry.get("role")}
# Storage information for disk migration
storage_target: {entry.get("target_store", "shared")}
storage_current: {entry.get("current_store", "shared")}
storage_needs_migration: {entry.get("needs_migration", False)}
'''
    with open(hv_file, "w") as f:
        f.write(content)
    created.append(hv_file)

if created:
    print("host_vars created:")
    for path in created:
        print(f" - {path}")
else:
    print("no host_vars created (nothing matched)")

if nodes_needing_migration:
    print(f"\n--- Storage Migration Info ---")
    print(f"Nodes needing storage migration ({len(nodes_needing_migration)}):")
    for ip in nodes_needing_migration:
        entry = ip_to_entry[ip]
        print(f"  - {entry['name']} ({ip}): {entry['current_store']} -> {entry['target_store']}")
    
    print(f"\nRun storage migration playbook:")
    print(f"  ansible-playbook -i ansible/hosts ansible/storage-migration.yml")
else:
    print(f"\nNo storage migration needed - all disks are in target locations")